### PR TITLE
Implement the `Socket` interface on Windows

### PR DESCRIPTION
**Pull request by djdv**
This is pretty much a direct copy/paste port of the Unix implementation, which gets `bitmagnet.exe` building on Windows.

Running `bitmagnet.exe` shows it connecting and communicating with my locally running postgres server, so I assume it works.
However, I don't think I have my database set up so I can't test further.

Before moving this out of draft, I need to either figure out the right way to initialize the DB, or try and fetch it from the docker image. Or have someone else confirm this branch works as expected.

---

For context this is what I did for the database:
```
initdb bitmagnet
postgres -D bitmagnet
createdb bitmagnet
createuser postgres
```

Was seeing "permission denied for schema public" so I executed these queries
```
GRANT ALL PRIVILEGES ON DATABASE bitmagnet TO postgres;
GRANT ALL ON SCHEMA public TO postgres;
```

but am still seeing:
```
postgres.exe -D bitmagnet
2024-02-19 02:10:44.630 EST [24780] LOG:  starting PostgreSQL 16.2, compiled by Visual C++ build 1937, 64-bit
2024-02-19 02:10:44.636 EST [24780] LOG:  listening on IPv6 address "::1", port 5432
2024-02-19 02:10:44.636 EST [24780] LOG:  listening on IPv4 address "127.0.0.1", port 5432
2024-02-19 02:10:44.700 EST [972] LOG:  database system was shut down at 2024-02-19 02:10:42 EST
2024-02-19 02:10:44.727 EST [24780] LOG:  database system is ready to accept connections
2024-02-19 02:10:52.259 EST [22348] ERROR:  relation "goose_db_version" does not exist at character 36
2024-02-19 02:10:52.259 EST [22348] STATEMENT:  SELECT version_id, is_applied from goose_db_version ORDER BY id DESC
2024-02-19 02:10:52.260 EST [22348] ERROR:  permission denied for schema public at character 14
2024-02-19 02:10:52.260 EST [22348] STATEMENT:  CREATE TABLE goose_db_version (
                        id serial NOT NULL,
                        version_id bigint NOT NULL,
                        is_applied boolean NOT NULL,
                        tstamp timestamp NULL default now(),
                        PRIMARY KEY(id)
```

### CODE REVIEW

**Comment by vadimkim** [comment]
I compiled and run this PR on Windows 10 with DB running in container. Stability is a problem. From time to time bitmagnet.exe is falling down due to socket read error exception (on the screenshot):
 
image

**Comment by mgdigital** [comment]
Thanks for your work on this @djdv - I know it's still in draft but I'd like to get it merged to an internal PR branch so it can be tested by Windows users along with some other fixes.

**Comment by mgdigital** [comment]
https://github.com/bitmagnet-io/bitmagnet/pull/203

**Comment by djdv** [comment]
@vadimkim I haven't looked into the calling code for this yet, but I'm assuming it's something similar to this: https://github.com/anacrolix/dht/issues/16
IIRC, basically a temporary error is being returned, and needs to be handled (either retry some operation or ignore the error, depending). That kind of error handling likely isn't set up in the caller yet, and probably panics instead.

**Pull request merged**
