### PR TITLE
Add unofficial packages section

### PR DESCRIPTION
**Pull request by mgdigital**

### CODE REVIEW

**Comment by mgdigital** [comment]
Hey @davispuh, can I check if you're happy with this or would you rather not be linked here?

**Comment by mgdigital** [comment]
Hi @xstar97, can I check if you're happy with the wording here?

**Comment by xstar97** [comment]
can add a reference that its a 3rd party catalog and not directly associated with TrueNas Scale, thanks.

**Comment by Ornias1993** [comment]
TrueCharts is not just a TrueNAS SCALE packaging project.
We make a multitude of packages, we do not want to be associated by, what is essentially, the worst project we support.

**Comment by Ornias1993** [comment]
Besides this pointer, it's also called "TrueNAS SCALE App", not "Chart"

**Comment by mgdigital** [comment]
> TrueCharts is not just a TrueNAS SCALE packaging project.

Right, but this is not your marketing page!

> Besides this pointer, it's also called "TrueNAS SCALE App", not "Chart"
> we do not want to be associated by, what is essentially, the worst project we support

Right forgive me but I've no idea about the underlying situation or your product offering and the terminology used, but have changed the wording to "App".

**Comment by Ornias1993** [comment]
> > TrueCharts is not just a TrueNAS SCALE packaging project.
> 
> Right, but this is not your marketing page!

As you can read in the other PR, I also scolded the submitter for taking over your page.
There is no reason to attack me like that.

> > Besides this pointer, it's also called "TrueNAS SCALE App", not "Chart"
> > we do not want to be associated by, what is essentially, the worst project we support
> 
> Right forgive me but I've no idea about the underlying situation or your product offering and the terminology used, but have changed the wording to "App".

To be clear:
We're not a company, nor do we offer products. We're a volunteer community and wanted to boost the quality/availability of a project we liked.
The "Apps" thing is decided by iX-Systems, an unrelated company. Not our choice.

**Comment by Ornias1993** [comment]
I'm not so sure if we would want to go this route.

We wanted to boost this project by appending your docs with good solid step-by-step instructions that covers the platforms we build for. 

The link points to a page that has no relevance for your users at all, nor covers the  TrueSCALE App specifically.
We can make some page to link to.

But we rather helped your community by adding a solid step-by-step process.

**Comment by Ornias1993** [comment]
After some discussion, we would like the reference to our project removed.
As it doesn't point to a TrueNAS SCALE specific page it will needlessly confuse users.

**Comment by Ornias1993** [comment]
@mgdigital Thank you, we will add links to any guides we would make in the future accordingly.
But as we currently have non, removing it is the best option.

**Comment by davispuh** [comment]
> Hey @davispuh, can I check if you're happy with this or would you rather not be linked here?

I don't think GitHub's markdown parser supports such property `{:target="\_blank"}`. Also package's name should be easily visible so people can install it right away. I would format it like this
```md
* `bitmagnet-git` [AUR package](https://aur.archlinux.org/packages/bitmagnet-git)
```

On Arch Linux you want to just copy name and paste in your favorite helper, eg. `yay -S bitmagnet-git` and it will be installed :)

**Comment by mgdigital** [comment]
> > Hey @davispuh, can I check if you're happy with this or would you rather not be linked here?
> 
> I don't think GitHub's markdown parser supports such property `{:target="\_blank"}`. 
> 

Yes there are various other things GitHub doesn't support either including the internal links. So this is really only intended to be built by Jekyll and read on the website. It's consistent with all the other external links. If there's a way to make everything cross-compatible between Jekyll and GitHub I'm interested but there didn't seem to be - maybe I just didn't look hard enough?

> Also package's name should be easily visible so people can install it right away.
> On Arch Linux you want to just copy name and paste in your favorite helper, eg. `yay -S bitmagnet-git` and it will be installed :)

Done.

BTW I am going to add a command like `bitmagnet config yaml` that can be piped to a template yaml file as part of any package's build process, that way it will always be up-to-date.

As for the systemd service example and the linux package situation in general, I need to understand more about different package management options and try things myself before officially supporting anything. I've abandoned the idea of Flatpack due to things I've read about it. Nix is looking like a good option at the moment that would cover a lot of platforms at once...

**Comment by davispuh** [comment]
> If there's a way to make everything cross-compatible between Jekyll and GitHub I'm interested but there didn't seem to be - maybe I just didn't look hard enough?

I'm not really familiar with these things either. I can't think of anything other than have separate compilation step but that seems like waste of time since basically you would have 2 copies in Git :smile: one raw and one compiled for GitHub.


> BTW I am going to add a command like bitmagnet config yaml that can be piped to a template yaml file as part of any package's build process, that way it will always be up-to-date.

Nice! :ok_hand: 

> As for the systemd service example and the linux package situation in general, I need to understand more about different package management options and try things myself before officially supporting anything. I've abandoned the idea of Flatpack due to things I've read about it. Nix is looking like a good option at the moment that would cover a lot of platforms at once...

I think simplest approach is just care what you use yourself and for everything else let community create packages and so on.

**Comment by Ornias1993** [comment]
> > But we rather helped your community by adding a solid step-by-step process.
> 
> Seemed like it was the other way round and that you'd asked us to add a link to your project...

I, very much, doubt users start running TrueNAS SCALE, TrueCharts or a kubernetes cluster because they want to run bitmagnet. If they do that would be quite silly. Besides that I already know of quite a few people that explicitly started using bitmagnet because our staff promoted it on our Discord.

Taking into account the accusations of linkbegging, we're sorry for having put time and effort into trying to help out the bitmagnet community running it on more platforms.  Other projects where always very appreciative, when we put effort to write install guides for their docs.

**Pull request merged**
