### PR TITLE
Implement multiplatform builds (#18)

### PR DESCRIPTION
**Pull request by mgdigital**
* Initial multiplatform build

* Change image name for pr

* Fix prettier errors

* Handle semver

---------

### CODE REVIEW

**Comment by Thanzex** [comment]
I can see it's still adding the `latest` to the beta tag, I did test this condition and the latest wasn't applied as you can see here 
https://github.com/Thanzex/bitmagnet/actions/runs/6432243372/job/17466684475#step:3:40
Also, i can't quite figure out why it's failing now when it was fine a few minutes ago

**Comment by mgdigital** [comment]
> i can't quite figure out why it's failing now when it was fine a few minutes ago

I'm trying a few things. I think we were editing the metadata-action in the wrong place, there's another one further down - just trying a new build. The docs don't quite apply to doing a push-by-digest so.....

**Comment by mgdigital** [comment]
Okay I've now got the lack-of-latest-tag working on the most recent beta. Pushing a non-beta now, if that works we should be good to merge.

**Comment by mgdigital** [comment]
Woop it works! Thanks for your help @Thanzex

**Pull request merged**
